// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-amCLDADGNMKjNB-ffFDzo7a4jGda5ZI',
    appId: '1:246081489623:web:4ca8ef401097ea602b3e92',
    messagingSenderId: '246081489623',
    projectId: 'workout-lidha-skripsi',
    authDomain: 'workout-lidha-skripsi.firebaseapp.com',
    storageBucket: 'workout-lidha-skripsi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChPP9JEMCyjZ3SZbp3wBKMCiWOgdCAS4A',
    appId: '1:246081489623:android:eed206bb290617062b3e92',
    messagingSenderId: '246081489623',
    projectId: 'workout-lidha-skripsi',
    storageBucket: 'workout-lidha-skripsi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIx-29-2vDQMREqCKNZV36fNF9WofmFG4',
    appId: '1:246081489623:ios:dee05874bb7b6be62b3e92',
    messagingSenderId: '246081489623',
    projectId: 'workout-lidha-skripsi',
    storageBucket: 'workout-lidha-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIx-29-2vDQMREqCKNZV36fNF9WofmFG4',
    appId: '1:246081489623:ios:dee05874bb7b6be62b3e92',
    messagingSenderId: '246081489623',
    projectId: 'workout-lidha-skripsi',
    storageBucket: 'workout-lidha-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-amCLDADGNMKjNB-ffFDzo7a4jGda5ZI',
    appId: '1:246081489623:web:7bea046591706e312b3e92',
    messagingSenderId: '246081489623',
    projectId: 'workout-lidha-skripsi',
    authDomain: 'workout-lidha-skripsi.firebaseapp.com',
    storageBucket: 'workout-lidha-skripsi.firebasestorage.app',
  );
}
